[[graphs]]
type = "CantitruncatedRegularPolyhedron"
name = "cantitruncated_dodecahedron"
id = "g1"

[video]
end_pause_frames = 0

[drawing]
scale = 100
line_width = 1
line_color = [230, 230, 230]
background_color = [20, 20, 20]
focal_length = 50

[[initial]]
offset = [0, 1, 0]
target = "g1"

[[actions]]
type = "rotate_complexly"
rotations = [
  { plane = [0, 2], angle = 360, duration = 120 },
  # { plane = [1, 2], angle = 360, duration = 120 },
  # { plane = [1, 3], angle = 90, duration = 120 },
  # { plane = [2, 3], angle = 180, duration = 120 },
  # { plane = [0, 3], angle = 270, duration = 120 },
  # { plane = [0, 1], angle = 360, duration = 120 }
]
start = 0
ease = "linear"
target = "g1"

[[actions]]
type = "move"
offset = [0, -2, 0]
duration = 30
start = 0
target = "g1"

[[actions]]
type = "move"
offset = [0, 2, 0]
duration = 30
start = 30
target = "g1"

[[actions]]
type = "move"
offset = [0, -2, 0]
duration = 30
start = 60
target = "g1"

[[actions]]
type = "move"
offset = [0, 2, 0]
duration = 30
start = 90
target = "g1"
