[[graphs]]
type = "GreatRhombiRectifiedRegularPolyhedron"
name = "great_rhombi_rectified_icosahedron"
id = "g1"

[video]
fps = 30
width = 1200
height = 1200
end_pause_frames = 0

[drawing]
scale = 120
line_width = 1
line_color = [230, 230, 230]
background_color = [20, 20, 20]
focal_length = 10

[[actions]]
type = "rotate_complexly"
rotations = [
  { plane = [0, 2], angle = 360, duration = 120 },
]
start = 0
target = "g1"
