[vertices]
type = "Hypercube"
dimensions = 4

[video]
fps = 30
width = 1920
height = 1080
end_pause_frames = 60

[drawing]
scale = 120
line_width = 5
line_color = [230, 230, 230]
background_color = [20, 20, 20]
focal_length = 7

[initial]
rotations = [
    { plane = [0, 2], angle = 45 }
]
offset = [1, 1, 1, 1]

[[actions]]
type = "move"
offset = [-2.0, -1.0, -1.0, -3.0]
duration = 150
start = 0

[[actions]]
type = "rotate"
plane = [0, 2]
angle = 360
center = [2, 0, 0, 0]
duration = 100
start = 150

[[actions]]
type = "rotate_complex"
rotations = [
    { plane = [0, 2], angle = -45, duration = 200 },
    { plane = [2, 3], angle = 360, duration = 200 }
]
start = 250

[[actions]]
type = "move"
offset = [1.0, 0.0, 0.0, 2.0]
duration = 150
start = 250
