[[graphs]]
type = "Text"
text = "P"
font_path = "/storage/emulated/0/下载/ws.git/unicode快闪/Sarasa-Mono-SC-Regular.ttf"
elevations = [
  { type = 'cylindrify', height = 0.1 }
]
# type = "CantellatedRegularPolyhedron"
# name = "cantellated_dodecahedron"
id = "g1"

[video]
width = 1080
height = 1080

[drawing]
scale = 250
line_width = 1
line_color = [230, 230, 230]
background_color = [20, 20, 20]
focal_length = 5

[[initial]]
rotations = [
    { plane = [0, 2], angle = 45 }
]
target = "g1"

[[actions]]
type = "rotate"
plane = [0, 2]
angle = 360
duration = 180
start = 0
target = 'g1'
