[[graphs]]
type = "RegularPolygon"
edge_count = 3
elevations = [
  { type = 'conify', height = 2 },
  { type = 'cylindrify', height = 2 }
]
id = "g1"

[video]
width = 1080
height = 1080

[drawing]
scale = 500
line_width = 1
line_color = [230, 230, 230]
background_color = [20, 20, 20]
focal_length = 5

[[actions]]
type = "rotate"
plane = [0, 2]
angle = 360
duration = 180
start = 0
target = 'g1'

[[actions]]
type = "rotate"
plane = [2, 3]
angle = 360
duration = 180
start = 45
target = 'g1'
