[[graphs]]
type = "RegularPolyhedron"
name = "hexahedron"
id = "g1"

[video]
fps = 30
width = 1920
height = 1080
end_pause_frames = 60

[drawing]
scale = 200
line_width = 1
line_color = [230, 230, 230]
background_color = [20, 20, 20]
focal_length = 12

[[actions]]
type = "rotate"
plane = [0, 2]
angle = 360
duration = 100
start = 0
target = "g1"
