[[graphs]]
type = "RegularPolyhedronCompounds"
name = "small_icosicosahedron"
id = "g1"

[video]
fps = 30
width = 1920
height = 1080
end_pause_frames = 60

[drawing]
scale = 650
line_width = 5
line_color = [230, 230, 230]
background_color = [20, 20, 20]
focal_length = 7

[[actions]]
type = "rotate"
plane = [0, 2]
angle = 360
duration = 400
start = 0
target = "g1"
